"""empty message

Revision ID: 126ae6b8bd1
Revises: 27cdae2d8b6
Create Date: 2016-06-30 10:19:39.922639

"""

# revision identifiers, used by Alembic.
revision = '126ae6b8bd1'
down_revision = '27cdae2d8b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sponsor')
    ### end Alembic commands ###
