"""empty message

Revision ID: 17bb931464c
Revises: 4abf6f370fc
Create Date: 2016-05-15 17:14:35.813216

"""

# revision identifiers, used by Alembic.
revision = '17bb931464c'
down_revision = '4abf6f370fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
