"""empty message

Revision ID: 1f74d62b264
Revises: 4b7050c57aa
Create Date: 2016-06-07 15:51:13.488065

"""

# revision identifiers, used by Alembic.
revision = '1f74d62b264'
down_revision = '4b7050c57aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
