"""empty message

Revision ID: 27cdae2d8b6
Revises: 1f74d62b264
Create Date: 2016-06-07 08:13:37.949249

"""

# revision identifiers, used by Alembic.
revision = '27cdae2d8b6'
down_revision = '1f74d62b264'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
