"""empty message

Revision ID: 36516ad2f2c
Revises: 17bb931464c
Create Date: 2016-05-17 20:17:52.959143

"""

# revision identifiers, used by Alembic.
revision = '36516ad2f2c'
down_revision = '17bb931464c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
