"""empty message

Revision ID: 4560804bcbd
Revises: d35d7aad80
Create Date: 2016-06-30 12:18:47.170683

"""

# revision identifiers, used by Alembic.
revision = '4560804bcbd'
down_revision = 'd35d7aad80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsor', sa.Column('website', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsor', 'website')
    ### end Alembic commands ###
