"""empty message

Revision ID: 4abf6f370fc
Revises: None
Create Date: 2016-05-15 17:10:33.614352

"""

# revision identifiers, used by Alembic.
revision = '4abf6f370fc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
