"""empty message

Revision ID: 4b7050c57aa
Revises: 36516ad2f2c
Create Date: 2016-06-07 15:49:26.148355

"""

# revision identifiers, used by Alembic.
revision = '4b7050c57aa'
down_revision = '36516ad2f2c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('url', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price', 'url')
    ### end Alembic commands ###
